// Generated by https://quicktype.io

export interface IResUsuario {
    total:    number;
    Usuarios: IUsuario[];
}

export interface IUsuario {
    datos:      IDatos;
    _id?:        string;
    username:   string;
    contrasena: string;
    estado?:     boolean;
    email:      string;
    telefono:   string;
    admin?: Boolean;
    __v?:        number;
}

export interface IDatos {
    nombre:   string;
    apellido: string;
    cedula:   string;
    nivel:    number;
    paralelo: string;
}
