version: '3'

services:
  aulas:
    build: ./aulas
    volumes:
      - ./aulas:/app
    environment:
      - db=mongodb://dbAulas/Horario
    depends_on:
      - dbAulas
  asignaturas:
    build: ./asignaturas
    volumes:
      - ./asignaturas:/app
    environment:
      - db=mongodb://dbAsignaturas/Horario
    depends_on:
      - dbAsignaturas
  docentes:
    build: ./docentes
    volumes:
      - ./docentes:/app
    environment:
      - db=mongodb://dbDocentes/Horario
    depends_on:
      - dbDocentes
  usuarios:
    build: ./usuarios
    volumes:
      - ./usuarios:/app
    environment:
      - db=mongodb://dbUsuarios/Horario
    depends_on:
      - dbUsuarios
  horarios:
    build: ./horarios
    volumes:
      - ./horarios:/app
    environment:
      - db=mongodb://dbHorarios/Horario
    depends_on:
      - dbHorarios
  registros:
    build: ./registros
    volumes:
      - ./registros:/app
    environment:
      - db=mongodb://dbRegistros/Horario
    depends_on:
      - dbRegistros

  dbAulas:
    image: mongo
    ports:
      - "27017:27017"
  dbAsignaturas:
    image: mongo
    ports:
      - "27018:27017"
  dbDocentes:
    image: mongo
    ports:
      - "27019:27017"
  dbUsuarios:
    image: mongo
    ports:
      - "27020:27017"
  dbHorarios:
    image: mongo
    ports:
      - "27021:27017"
  dbRegistros:
    image: mongo
    ports:
      - "27022:27017"

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - aulas
      - docentes
      - asignaturas
      - usuarios
      - horarios
      - registros