version: "3"

services:
  web:
    container_name: horario
    build: .
    restart: always
    ports:
      - "8000:8000"
    links:
      - database
    environment:
      - db=mongodb://database/Horario
    volumes:
      - .:/usr/src/app
  database:
    container_name: mongoDB
    image: mongo
    ports:
      - "27018:27017"
    restart: always
    command: --quiet --logpath /dev/null